# Generated by Django 5.2.9 on 2025-12-03 14:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('new_companies', models.PositiveIntegerField(default=0)),
                ('new_jobs', models.PositiveIntegerField(default=0)),
                ('new_applications', models.PositiveIntegerField(default=0)),
                ('chat_messages', models.PositiveIntegerField(default=0)),
                ('matches_created', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Metricas do Site',
                'verbose_name_plural': 'Metricas do Site',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Anos de experiencia'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='cnpj',
            field=models.CharField(blank=True, help_text='CNPJ da empresa', max_length=18),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Notas sobre a verificacao'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Separe as habilidades por virgula'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10 funcionarios'), ('11-50', '11-50 funcionarios'), ('51-200', '51-200 funcionarios'), ('201-500', '201-500 funcionarios'), ('500+', 'Mais de 500 funcionarios')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProblemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bug', 'Bug/Erro'), ('feature', 'Sugestao de Funcionalidade'), ('account', 'Problema com Conta'), ('job', 'Problema com Vaga'), ('match', 'Problema com Match'), ('chat', 'Problema com Chat'), ('other', 'Outro')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Critica')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('in_progress', 'Em Andamento'), ('resolved', 'Resolvido'), ('closed', 'Fechado')], default='open', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Notas do administrador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_problems', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True, default='O site esta em manutencao. Voltaremos em breve!')),
                ('maintenance_end_time', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuracoes do Site',
                'verbose_name_plural': 'Configuracoes do Site',
            },
        ),
    ]
