# Generated by Django 5.2.9 on 2025-12-08 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_candidate_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome canonico da habilidade', max_length=100, unique=True)),
                ('aliases', models.TextField(blank=True, help_text='Variacoes conhecidas, separadas por virgula')),
                ('category', models.CharField(blank=True, help_text='Categoria da habilidade', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Habilidade Canonica',
                'verbose_name_plural': 'Habilidades Canonicas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Criacao'), ('update', 'Atualizacao'), ('delete', 'Exclusao'), ('approve', 'Aprovacao'), ('reject', 'Rejeicao'), ('maintenance_on', 'Manutencao Ativada'), ('maintenance_off', 'Manutencao Desativada'), ('login', 'Login'), ('logout', 'Logout'), ('status_change', 'Mudanca de Status')], max_length=30)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('application_status', 'Status da Candidatura'), ('company_approved', 'Empresa Aprovada'), ('company_rejected', 'Empresa Rejeitada'), ('new_application', 'Nova Candidatura'), ('new_message', 'Nova Mensagem'), ('system', 'Sistema')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificacao',
                'verbose_name_plural': 'Notificacoes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillCorrectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_term', models.CharField(max_length=100)),
                ('corrected_term', models.CharField(blank=True, max_length=100)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('was_auto_corrected', models.BooleanField(default=False)),
                ('needs_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Correcao de Habilidade',
                'verbose_name_plural': 'Logs de Correcao de Habilidades',
                'ordering': ['-created_at'],
            },
        ),
    ]
