# Generated by Django 5.2.9 on 2025-12-02 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('beginner', 'Iniciante'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado')], default='beginner', max_length=20)),
                ('area', models.CharField(choices=[('programming', 'Programação'), ('data_science', 'Data Science'), ('design', 'Design'), ('marketing', 'Marketing'), ('management', 'Gestão'), ('languages', 'Idiomas'), ('soft_skills', 'Soft Skills'), ('other', 'Outros')], default='programming', max_length=30)),
                ('duration_hours', models.PositiveIntegerField(help_text='Carga horária em horas')),
                ('external_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('skills_taught', models.TextField(help_text='Habilidades ensinadas, separadas por vírgula')),
                ('instructor', models.CharField(blank=True, max_length=100)),
                ('is_free', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Não Iniciado'), ('in_progress', 'Em Andamento'), ('completed', 'Concluído')], default='not_started', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0, help_text='Progresso em porcentagem (0-100)')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
